# Site
name: 'Mahesh Sathiamoorthy'
description: 'Homepage and blog of Mahesh Sathiamoorthy'
logo: 'assets/images/logo.png'
favicon32: 'assets/images/favicon-32x32.png'
faviconapple: 'assets/images/apple-touch-icon.png'
favicon16: 'assets/images/favicon-16x16.png'
webmanifest: 'assets/images/site.webmanifest'

baseurl: ''
disqus: 'mindisblown'
email: 'mahesh@smahesh.com'
mailchimp-list: 'https://mailchi.mp/a48618289422/subscribe-for-newsletter'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins_dir: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  
authors:
    mahesh:
      name:           Mahesh
      site:           https://smahesh.com
      avatar:         /assets/images/Mahesh-avatar.jpg
      bio:            "I think and read about Technology and the Human Mind. I am currently an ML engineer at Google, but the opinions here are my own and do not reflect that of my employer."
      email:          mahesh@smahesh.com
      twitter:        https://twitter.com/madiator
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: mahesh
      avatar: /assets/images/Mahesh-avatar.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]